version: '3.1'
services:
  web:
    build: web
    image: web_image
    container_name:  web_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/currencies
      - SPRING_DATASOURCE_USERNAME=Alexey
      - SPRING_DATASOURCE_PASSWORD=AlexeyVLZ

  db:
    image: postgres:14-alpine
    container_name: db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=Alexey
      - POSTGRES_PASSWORD=AlexeyVLZ
      - POSTGRES_DB=currencies

  client:
    build: client
    image: client_image
    container_name: client_container
    ports:
      - "9090:9090"
    depends_on:
          - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/currencies
      - SPRING_DATASOURCE_USERNAME=Alexey
      - SPRING_DATASOURCE_PASSWORD=AlexeyVLZ
      - STATS_SERVER_URL=http://web:9090
