CREATE TABLE IF NOT EXISTS currency_pair
(
    currency_pair_id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    base_charcode VARCHAR(5) NOT NULL,
    quoted_charcode VARCHAR(5) NOT NULL,
    description VARCHAR(100) NOT NULL,
    CONSTRAINT pk_currency_pair PRIMARY KEY (currency_pair_id),
    CONSTRAINT unique_currency_pair UNIQUE (base_charcode, quoted_charcode)
);

CREATE TABLE IF NOT EXISTS exchange_rate
(
    exchange_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rate_date TIMESTAMP NOT NULL ,
    rate_value FLOAT NOT NULL ,
    currency_pair_id INTEGER NOT NULL,
    CONSTRAINT pk_exchange_rate PRIMARY KEY (exchange_rate_id),
    CONSTRAINT fk_exchange_rate_on_currency_pair FOREIGN KEY (currency_pair_id) REFERENCES currency_pair(currency_pair_id),
    CONSTRAINT unique_rate_value_of_date UNIQUE (rate_date, currency_pair_id)
);